### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by sofire** [jdoe0/ankisyncd#1]
When I update Anki to 2.1.11, there is an error.

ValueError: invalid literal for int() with base 10: '11 (3cf770c7)'
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 604, in __call__
    result = self._execute_handler_method_in_thread(url, data, session)
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 681, in _execute_handler_method_in_thread
    result = thread.execute(run_func)
  File "/root/ankisyncd/ankisyncd/thread.py", line 52, in execute
    raise ret
  File "/root/ankisyncd/ankisyncd/thread.py", line 71, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/root/ankisyncd/ankisyncd/collection.py", line 39, in execute
    ret = func(*args, **kw)
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 672, in run_func
    res = handler_method(**keyword_args)
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 82, in meta
    if self._old_client(cv):
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 68, in _old_client
    version_int = [int(x) for x in version.split('.')]
  File "/root/ankisyncd/ankisyncd/sync_app.py", line 68, in <listcomp>
    version_int = [int(x) for x in version.split('.')]

I try to fix it, and it works for me.
In /root/ankisyncd/ankisyncd/sync_app.py

 72         #remove string like "2.1.11 (3cf770c7)"
 73         version = version.split(" ")[0]
 74         version_int = [ int(str(x).translate(None, string.ascii_letters))
 75                         for x in version.split('.') ]

**Comment by jdoe0** [comment]
Should be fixed now.
